server:
  port: 8899
  tomcat:
    connection-timeout: 18000000
spring:
  application:
    name: zdm
key:
  #支持两种配置：pushPlus或者serverJ，二选一
  #pushPlus参考：http://pushplus.hxtrip.com/，不限制次数，不用github账号
  #serverJ参考：http://sc.ftqq.com/3.version ，需要github账号，限制次数
  type: pushPlus
  # 对应平台的key
  value: 9b343***
#爆料人id：https://zhiyou.smzdm.com/member/9687682701/baoliao/ 参考这个链接
uid: 9687682701
# 频率十秒一次  ，
corn: 0/10 * * * * ?
# 三十秒一次
#corn: 0/30 * * * * ?
